# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:

  # Run node tests on past node versions
  - template: ./templates/node-build-template.yml
    parameters:
      nodeVersion: 12.x
      name: Node12_Tests
  - template: ./templates/node-build-template.yml
    parameters:
      nodeVersion: 14.x
      name: Node10_Tests

  # Run the E2E tests on local simulators across different ios and xcode versions
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iphone_13_7
      iosVersion: 13.7
      xcodeVersion: 11.7
      tvosName: AppleTV_13_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS 10.15'
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iphone_13_0
      iosVersion: 13.0
      xcodeVersion: 11
      tvosName: AppleTV_13
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS 10.15'
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iphone_12_4
      iosVersion: 12.4
      xcodeVersion: 10.3
      tvosName: AppleTV_12_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS 10.14'
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iphone_12_0
      iosVersion: 12.0
      xcodeVersion: 10
      tvosName: AppleTV_12_0
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS 10.14'